name: 编译构建
on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - ".github/workflows/build.yml"
      - "go.mod"
      - "go.sum"
      - "**/*.go"
  pull_request:
    branches:
      - "main"

env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jobs:
          - { goos: darwin, goarch: arm64, output: arm64 }
          - { goos: darwin, goarch: amd64, output: amd64 }

          - { goos: linux, goarch: "386", output: "386" }
          - { goos: linux, goarch: amd64, output: amd64 }
          - { goos: linux, goarch: arm64, output: arm64 }
          - { goos: linux, goarch: arm, goarm: "5", output: armv5 }
          - { goos: linux, goarch: arm, goarm: "6", output: armv6 }
          - { goos: linux, goarch: arm, goarm: "7", output: armv7 }
          - { goos: linux, goarch: loong64, output: loong64 }
          - { goos: linux, goarch: riscv64, output: riscv64 }

          - { goos: windows, goarch: amd64, output: amd64 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 设置 Go 版本
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: 编译
        env:
          GOOS: ${{matrix.jobs.goos}}
          GOARCH: ${{matrix.jobs.goarch}}
          GOARM: ${{matrix.jobs.goarm}}
        run: |
          go build  -o /tmp/ ./cmd/app
          make builder || true
          if [ "${{matrix.jobs.goos}}" = "windows" ]; then
            cp dist/ikuai-exporter.exe ikuai-exporter-${{matrix.jobs.goos}}-${{matrix.jobs.output}}.exe
            zip -r dist/ikuai-exporter-${{matrix.jobs.goos}}-${{matrix.jobs.output}}.zip ikuai-exporter-${{matrix.jobs.goos}}-${{matrix.jobs.output}}.exe
          else
            cp dist/ikuai-exporter dist/ikuai-exporter-${{matrix.jobs.goos}}-${{matrix.jobs.output}}
            gzip -c dist/ikuai-exporter-${{matrix.jobs.goos}}-${{matrix.jobs.output}} > ikuai-exporter-${{matrix.jobs.goos}}-${{matrix.jobs.output}}.gz
          fi

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.jobs.goos }}-${{ matrix.jobs.output }}"
          path: |
            ikuai-exporter*.gz
            ikuai-exporter*.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.sha }}
          body: 由提交${{ github.sha }}自动触发编译生成的Release。
          files: |
            ikuai-exporter*.gz
            ikuai-exporter*.zip
      - name: 删除旧的工作流
        uses: Mattraks/delete-workflow-runs@main
