name: Docker镜像构建

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - '.github/workflows/composer.yml'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - '**/*.go'
  pull_request:
    branches:
      - 'main'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            tossp/ikuai-exporter
            ghcr.io/tossp/ikuai-exporter
          tags: |
            type=edge
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.title=ikuai-exporter
            org.opencontainers.image.description=Export Ikuai API data to Prometheus
            org.opencontainers.image.vendor=TossP.com
      - name: 登录 DockerHub 容器镜像
        uses: docker/login-action@v3
        with:
          username: tossp
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 登录 GitHub 容器镜像
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3
      - name: 设置 Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: 查看可用平台
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: 构建 ikuai-exporter
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: 删除旧的工作流
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
